# Generated by Django 4.0.6 on 2024-03-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfeedback',
            name='buzzed',
            field=models.BooleanField(default=False),
        ),
    ]
