# Generated by Django 5.0.3 on 2024-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="", max_length=320),
        ),
    ]
