# Generated by Django 5.0.3 on 2024-05-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionfeedback",
            name="buzz_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="questionfeedback",
            name="interestingness_rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="questionfeedback",
            name="inversions",
            field=models.IntegerField(default=0),
        ),
    ]
