# Generated by Django 5.0.3 on 2024-05-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_questionfeedback_buzz_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, default="", max_length=320),
        ),
    ]
