# Generated by Django 5.0.3 on 2024-05-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_accept",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_antiprompt",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_regular_prompt",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_reject",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="page_cleaned",
            field=models.TextField(default=""),
        ),
    ]
