# Generated by Django 5.0.3 on 2024-05-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_question_answer_accept_question_answer_antiprompt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionfeedback",
            name="interestingness_rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                default=0,
            ),
        ),
    ]
