# Generated by Django 5.0.3 on 2024-07-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_questionfeedback_interestingness_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionfeedback",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
    ]
