# Generated by Django 5.0.3 on 2024-09-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_questionfeedback_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
