# Generated by Django 5.0.3 on 2024-09-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_question_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
