# Generated by Django 5.0.3 on 2024-09-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_question_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_human_written',
            field=models.BooleanField(default=False),
        ),
    ]
