# Generated by Django 4.0.6 on 2024-09-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_room_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uses_instructions',
            field=models.BooleanField(default=False),
        ),
    ]
