# Generated by Django 4.0.6 on 2024-09-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_instructions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructions',
        ),
        migrations.AddField(
            model_name='question',
            name='instructions_a',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='instructions_b',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
