# Generated by Django 4.0.6 on 2024-09-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_player_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='curr_room',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
    ]
