# Generated by Django 5.0.3 on 2024-09-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_player_curr_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLog',
            fields=[
                ('tool_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction_type', models.CharField(max_length=1)),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_query', models.TextField()),
                ('tool_result', models.JSONField()),
                ('tool_execution_status', models.TextField()),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
        ),
    ]
