# Generated by Django 5.0.3 on 2024-09-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_remove_toollog_question_remove_toollog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollog',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
