# Generated by Django 5.0.3 on 2024-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_toollog_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='document_context',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='uses_calculator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='uses_doc_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='uses_web_search',
            field=models.BooleanField(default=True),
        ),
    ]
