# Generated by Django 5.0.3 on 2024-10-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_question_document_context_question_uses_calculator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.TextField()),
                ('document_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
