# Generated by Django 5.0.3 on 2024-10-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_document_alter_user_name_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='split',
            field=models.TextField(default='all'),
        ),
    ]
