# Generated by Django 5.0.3 on 2024-10-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_room_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('correctness_score', models.FloatField()),
                ('seconds_taken', models.FloatField()),
            ],
        ),
    ]
