# Generated by Django 5.0.3 on 2024-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_leaderboardlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardlog',
            name='question_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboardlog',
            name='seconds_taken',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leaderboardlog',
            name='user_id',
            field=models.CharField(),
        ),
    ]
