# Generated by Django 5.0.3 on 2024-10-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_leaderboardlog_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='leaderboardlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.user'),
        ),
    ]
