# Generated by Django 5.0.3 on 2024-10-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_remove_leaderboardlog_user_id_leaderboardlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('playing', 'Playing'), ('contest', 'Contest'), ('instruct', 'Instruct'), ('compare', 'Compare')], default='idle', max_length=9),
        ),
    ]
