# Generated by Django 5.0.3 on 2024-10-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_comparisonfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='show_comparisons_before',
            field=models.BooleanField(null=True),
        ),
    ]
