# Generated by Django 5.0.3 on 2024-10-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_room_show_comparisons_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('is_bad_question', models.BooleanField()),
                ('is_bad_instruction', models.BooleanField()),
                ('is_bad_answer_verifier', models.BooleanField()),
                ('feedback', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
        ),
    ]
