# Generated by Django 5.0.3 on 2024-10-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_reportissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonfeedback',
            name='shown_first',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
