# Generated by Django 5.0.3 on 2024-10-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_remove_comparisonfeedback_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonfeedback',
            name='chosen_adjusted',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='comparisonfeedback',
            name='chosen_intruction',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
