# Generated by Django 5.0.3 on 2024-10-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_comparisonfeedback_chosen_adjusted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonfeedback',
            old_name='chosen_intruction',
            new_name='chosen_instruction',
        ),
    ]
