# Generated by Django 5.0.3 on 2024-10-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_rename_chosen_intruction_comparisonfeedback_chosen_instruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='player_map',
            new_name='instruction_map',
        ),
    ]
