# Generated by Django 5.0.3 on 2024-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_rename_player_map_room_instruction_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='curr_instructions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
