# Generated by Django 5.0.3 on 2024-10-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_room_curr_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='steps_seen',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
