# Generated by Django 5.0.3 on 2024-10-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_room_steps_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='curr_instructions',
        ),
        migrations.RemoveField(
            model_name='room',
            name='steps_seen',
        ),
        migrations.AddField(
            model_name='room',
            name='curr_instructions_a',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='curr_instructions_b',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='curr_instructions_letter',
            field=models.TextField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='steps_seen_a',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='steps_seen_b',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
