# Generated by Django 5.0.3 on 2024-10-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_remove_room_curr_instructions_remove_room_steps_seen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='curr_instructions_a',
            new_name='curr_subanswers_a',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='curr_instructions_b',
            new_name='curr_subanswers_b',
        ),
    ]
