# Generated by Django 5.0.3 on 2024-10-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_rename_curr_instructions_a_room_curr_subanswers_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toollog',
            name='did_comparison',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AnswerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('final_instructions_letter', models.TextField(max_length=1)),
                ('instructions_a', models.JSONField()),
                ('instructions_b', models.JSONField()),
                ('subanswers_a', models.JSONField()),
                ('subanswers_b', models.JSONField()),
                ('steps_seen_a', models.IntegerField()),
                ('steps_seen_b', models.IntegerField()),
                ('did_comparison', models.BooleanField()),
                ('is_correct', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
        ),
    ]
