# Generated by Django 5.0.3 on 2024-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_toollog_did_comparison_answerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardlog',
            name='did_comparison',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
