# Generated by Django 5.0.3 on 2024-10-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_leaderboardlog_did_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toollog',
            name='did_comparison',
        ),
    ]
