# Generated by Django 5.0.3 on 2024-10-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_remove_toollog_did_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='followed_plan',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
