# Generated by Django 5.0.3 on 2024-11-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_answerdata_followed_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='curr_query',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
