# Generated by Django 5.0.3 on 2024-11-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_room_curr_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportissue',
            name='is_frustrated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
