# Generated by Django 5.0.3 on 2024-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0048_reportissue_is_frustrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfeedback',
            name='guessed_generation_method',
            field=models.CharField(choices=[('human', 'Human-written'), ('ai', 'AI-generated'), ('attention_s', 'attention_s'), ('attention_p', 'attention_p'), ('tutorial', 'tutorial')], max_length=30),
        ),
    ]
