# Generated by Django 5.0.3 on 2024-12-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0049_alter_questionfeedback_guessed_generation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardlog',
            name='category',
            field=models.TextField(default='Everything'),
        ),
    ]
