# Generated by Django 5.0.3 on 2024-12-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0050_leaderboardlog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='category',
            field=models.TextField(default='Everything'),
        ),
    ]
