# Generated by Django 5.0.3 on 2024-12-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0051_answerdata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='is_final',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionfeedback',
            name='guessed_generation_method',
            field=models.CharField(choices=[('human', 'Human-written'), ('ai', 'AI-generated'), ('llama', 'llama'), ('qwen', 'qwen'), ('attention_s', 'attention_s'), ('attention_p', 'attention_p'), ('tutorial', 'tutorial')], max_length=30),
        ),
    ]
