# Generated by Django 5.0.3 on 2024-12-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0052_answerdata_is_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='guessed_answer',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='answerdata',
            name='true_answer',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_guess',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
