# Generated by Django 5.0.3 on 2024-12-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0053_answerdata_guessed_answer_answerdata_true_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardlog',
            name='tool_runtime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboardlog',
            name='total_time_taken',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboardlog',
            name='seconds_taken',
            field=models.FloatField(),
        ),
    ]
