# Generated by Django 5.0.3 on 2024-12-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0054_leaderboardlog_tool_runtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
