# Generated by Django 5.0.3 on 2025-01-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_user_experiment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='notes',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
