# Generated by Django 5.0.3 on 2025-01-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0057_answerdata_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='', max_length=320, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experiment_group',
            field=models.CharField(blank=True, choices=[('pairwise', 'Pairwise'), ('swap', 'Swap')], default=None, max_length=10, null=True),
        ),
    ]
