# Generated by Django 5.0.3 on 2025-01-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0058_user_password_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
