# Generated by Django 5.0.3 on 2025-01-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0059_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_preference',
            field=models.CharField(choices=[('Everything', 'Everything'), ('Science', 'Science'), ('History', 'History'), ('Literature', 'Literature'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Geography', 'Geography'), ('Fine Arts', 'Fine Arts'), ('Social Science', 'Social Science'), ('Mythology', 'Mythology'), ('Trash', 'Trash'), ('Multi-Hop', 'Multi-Hop'), ('Math', 'Math'), ('Long-Context', 'Long-Context')], default='Everything', max_length=30),
        ),
    ]
