# Generated by Django 5.0.3 on 2025-01-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0060_user_category_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfeedback',
            name='guessed_generation_method',
            field=models.CharField(choices=[('human', 'Human-written'), ('ai', 'AI-generated'), ('llama', 'llama'), ('qwen', 'qwen'), ('claude', 'claude'), ('commandr', 'commandr'), ('gpt', 'gpt'), ('attention_s', 'attention_s'), ('attention_p', 'attention_p'), ('tutorial', 'tutorial')], max_length=30),
        ),
    ]
