# Generated by Django 5.0.3 on 2025-01-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0061_alter_questionfeedback_guessed_generation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='history_idx',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='search_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
