# Generated by Django 5.0.3 on 2025-01-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0062_room_history_idx_room_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='history_idx',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
