# Generated by Django 5.0.3 on 2025-01-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0063_alter_room_history_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_scroll',
            field=models.BooleanField(default=True),
        ),
    ]
