# Generated by Django 5.0.3 on 2025-01-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0064_user_auto_scroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='curr_query_raw',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
