# Generated by Django 5.0.3 on 2025-01-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0065_room_curr_query_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wiki_token_num',
            field=models.IntegerField(default=1),
        ),
    ]
