# Generated by Django 5.0.3 on 2025-01-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0067_answerdata_timestamp_comparisonfeedback_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wiki_token_num',
        ),
    ]
