# Generated by Django 5.0.3 on 2025-01-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0068_remove_user_wiki_token_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='picked_letter',
            field=models.TextField(max_length=1, null=True),
        ),
    ]
